### ISSUE TITLE
Content Development Plan - Game Theory: Making Statistical Decisions

### ISSUE THREAD

**Issue by shreyagupta98** [bitprj/devrel#14]
<--- The DRI for this issue is the Content Developer. They will be responsible for keeping this issue up to date at all times --->

<-- Add this issue into the corresponding IMC Milestone -->

**[Step-By-Step Technical Blog Guide](https://hq.bitproject.org/how-to-write-a-technical-blog/)**

#### Step 1
- Title: {{Insert title here}}
- Topic: {{Insert topic here}}
- Sub-topic: {{Insert sub-topic here}}
- Structure: {{Insert structure here}}
- Description (5-7+ sentences): {{Insert description here}}
- Resources needed: {{Insert resources here}}

#### Step 2
- Describe target audience (3-5+ sentences):

#### Step 3
- Outline your learning/teaching process:
    - Beginning (2-3+ sentences):
    - Middle (2-3+ sentences):
    - End (2-3+ sentences):

- [ ] [Submit blog choice on airtable.](https://airtable.com/shrshp0d9sruL7l9J)
- [ ] Create Content Development Issue

**Comment by kylebegovich** [comment]
adding proposal now, see PR above^
