### ISSUE TITLE
Content Development Plan - Simple side-scrolling platformer game

### ISSUE THREAD

**Issue by shreyagupta98** [bitprj/devrel#18]
<--- The DRI for this issue is the Content Developer. They will be responsible for keeping this issue up to date at all times --->

<-- Add this issue into the corresponding IMC Milestone -->

**[Step-By-Step Technical Blog Guide](https://hq.bitproject.org/how-to-write-a-technical-blog/)**

#### Step 1
- Title: {{Insert title here}}
- Topic: {{Insert topic here}}
- Sub-topic: {{Insert sub-topic here}}
- Structure: {{Insert structure here}}
- Description (5-7+ sentences): {{Insert description here}}
- Resources needed: {{Insert resources here}}

#### Step 2
- Describe target audience (3-5+ sentences):

#### Step 3
- Outline your learning/teaching process:
    - Beginning (2-3+ sentences):
    - Middle (2-3+ sentences):
    - End (2-3+ sentences):

- [x] [Submit blog choice on airtable.](https://airtable.com/shrshp0d9sruL7l9J)
- [x] Create Content Development Issue

**Comment by Dadao-xiaoguaishou** [comment]
Step-By-Step Technical Blog Guide

### Step 1
- Title: {Simple side-scrolling platformer game}
- Topic: {Front-End Development}
- Sub-topic: {html/css}
- Structure: {step-by-step tutorial}
- Description (5-7+ sentences): {A intro to building games on the web. Creating a simple platformer game using p5.js and HTML. It might take about an hour to finish}
- Resources needed: {https://workshops.hackclub.com/platformer/}
### Step 2
- Describe the target audience (3-5+ sentences): People who are interested in building games. May need a little bit background in HTML.
### Step 3
- Beginning (2-3+ sentences): 
  - Show the demo of the final game
  - Give a short description of the game 
 
- Middle (2-3+ sentences):
  - Basic set up
  - Set the stage, add gravity
  - Creating a player (camera)
  - Add Obstacles
  - Ending game
  - Scorekeeping
  - Upgrading and customizing

- End (2-3+ sentences):
  - Some tips on sharing/publishing the game
  - Tips on hacking and customizing the game
